"""Write a UTAU voicebank (wavs + oto.ini + character.txt) from finished clips."""
from __future__ import annotations

import json
import re
import zipfile
from pathlib import Path

from . import audio
from .extract import Clip
from .morae import MORAE


def safe_name(name: str) -> str:
    n = re.sub(r"[^\w\- ぁ-んァ-ン一-龥]", "_", name.strip(), flags=re.UNICODE).strip(" ._")
    return n[:60] or "voice"


def oto_line(clip: Clip, sr: int = audio.SR_BANK) -> str:
    """One oto.ini entry. The wav is already cut to the usable range, so offset=0."""
    dur_ms = len(clip.audio) / sr * 1000
    pre = min(max(clip.split_s * 1000, 15.0), dur_ms * 0.6)
    consonant = min(pre + 45.0, dur_ms - 10.0)
    overlap = max(5.0, pre / 3)
    fields = [clip.mora.kana, 0, consonant, -dur_ms, pre, overlap]
    out = [fields[0]] + [f"{v:.1f}".rstrip("0").rstrip(".") if isinstance(v, float) else str(v) for v in fields[1:]]
    return f"{clip.mora.key}.wav=" + ",".join(out)


def _encode_sjis(text: str) -> bytes:
    try:
        return text.encode("cp932")
    except UnicodeEncodeError:
        return text.encode("utf-8")


def write_bank(clips: dict[str, Clip], out_dir: Path, name: str, report: dict) -> Path:
    """Create `<out_dir>/<name>/` and return its path."""
    root = out_dir / safe_name(name)
    root.mkdir(parents=True, exist_ok=True)
    lines = []
    order = {k: i for i, k in enumerate(MORAE)}
    for key in sorted(clips, key=lambda k: order[k]):
        c = clips[key]
        audio.write_wav(root / f"{key}.wav", c.audio, audio.SR_BANK)
        lines.append(oto_line(c))
    (root / "oto.ini").write_bytes(_encode_sjis("\n".join(lines) + "\n"))
    (root / "character.txt").write_bytes(_encode_sjis(f"name={name}\nimage=\nauthor=\nweb=\n"))
    (root / "readme.txt").write_text(
        f"{name}\nGenerated by Voice-2-UTAU.\n"
        "Single-mora hiragana CV voicebank (set the 'Aliases' to hiragana in your editor).\n"
        "voice2utau_report.json lists which samples are recordings and which are RVC/template fills.\n"
        "Check the licence/terms of the source voice and of any template used before distributing.\n",
        encoding="utf-8")
    (root / "voice2utau_report.json").write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    return root


def zip_bank(root: Path, zip_path: Path) -> Path:
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(root.rglob("*")):
            if p.is_file():
                zf.write(p, Path(root.name) / p.relative_to(root))
    return zip_path
